# Generated by Django 3.1.6 on 2021-02-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='date',
        ),
    ]
