# Generated by Django 3.1.6 on 2021-03-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210216_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='blog.image'),
        ),
    ]
