# Generated by Django 3.1.6 on 2021-03-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='user',
        ),
    ]
