# Generated by Django 3.1.6 on 2021-03-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210309_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='block_likes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='hide_likes',
            field=models.BooleanField(default=False),
        ),
    ]
