# Generated by Django 3.1.6 on 2021-03-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210309_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='draft',
        ),
    ]
