# Generated by Django 3.1.6 on 2021-03-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210309_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='block_likes',
        ),
    ]
