# Generated by Django 3.1.6 on 2021-03-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
