# Generated by Django 3.1.6 on 2021-03-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_survey_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='count',
        ),
        migrations.AddField(
            model_name='post',
            name='active_survey',
            field=models.BooleanField(default=False),
        ),
    ]
