# Generated by Django 3.1.6 on 2021-03-19 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_list_listitem_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='List',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.list'),
        ),
    ]
