# Generated by Django 3.1.6 on 2021-04-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20210410_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='removable',
            field=models.BooleanField(default=False),
        ),
    ]
