# Generated by Django 3.1.6 on 2021-04-13 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_list_removable'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='listitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
