# Generated by Django 3.1.6 on 2021-04-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20210413_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='removable',
            field=models.BooleanField(default=True),
        ),
    ]
