# Generated by Django 3.1.6 on 2021-04-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20210416_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='List',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.list'),
        ),
    ]
