# Generated by Django 3.1.6 on 2021-04-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_auto_20210416_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='post',
        ),
        migrations.RemoveField(
            model_name='view',
            name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
