# Generated by Django 3.1.6 on 2021-04-17 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_auto_20210416_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(default='Text', max_length=200, null=True)),
                ('description', models.CharField(default='Text', max_length=200, null=True)),
                ('onlyImage', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_block', to='blog.image')),
            ],
        ),
    ]
