# Generated by Django 3.1.6 on 2021-04-17 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_addon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addon', to='blog.image'),
        ),
    ]
