# Generated by Django 3.1.6 on 2021-04-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_auto_20210417_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
